// ACTION_TYPE = [domain]/[ENTITY or NOUN]_[VERB]/[STATE]
export const constants = {
  IMPORT_DATA: "app/IMPORT_DATA",
  IMPORT_DATA_SUCCESS: "app/IMPORT_DATA/SUCCESS",
  IMPORT_DATA_FAILURE: "app/IMPORT_DATA/FAILURE",
  FETCH_TWEET_DATA: "app/FETCH_TWEET_DATA",
  FETCH_TWEET_DATA_SUCCESS: "app/FETCH_TWEET_DATA/SUCCESS",
  FETCH_TWEET_DATA_FAILURE: "app/FETCH_TWEET_DATA/FAILURE",
  FETCH_USER_DATA: "app/FETCH_USER_DATA",
  FETCH_USER_DATA_SUCCESS: "app/FETCH_USER_DATA/SUCCESS",
  FETCH_USER_DATA_FAILURE: "app/FETCH_USER_DATA/FAILURE",
  DISPLAY_ALERT: "app/DISPLAY_ALERT",
};